[package]
name = "manager"
version = "0.0.1"
authors = ["Cron.near", "@trevorjtclarke"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
cron_schedule = "0.2.0"
near-contract-standards = "3.2.0"

[dev-dependencies]
near-sdk-sim = "3.1.0"
chrono = "~0.4"