name: Tests
on: push
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build
        env:
          IS_GITHUB_ACTION: true
        run: cargo +stable build --workspace --target wasm32-unknown-unknown --release
      - name: Copy wasm files
        uses: canastro/copy-file-action@master
        with:
          source: "target/wasm32-unknown-unknown/release/*.wasm"
          target: "res/"
          flags: '-r'
      - name: Run tests
        env:
          IS_GITHUB_ACTION: true
        run: cargo test --workspace -- --nocapture